name: Reserva Padel

on:
  schedule:
    # 🧠 pre-carga antes de medianoche
    - cron: '50 21 * * *'   # 23:50 local

    # 🔥 ventana crítica
    - cron: '58 21 * * *'   # 23:58 local
    - cron: '59 21 * * *'   # 23:59 local
    - cron: '0 22 * * *'    # 00:00 local
    - cron: '1 22 * * *'    # 00:01 local
    - cron: '2 22 * * *'    # 00:02 local

  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Instalar Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Ejecutar script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          USERS_JSON: ${{ secrets.USERS_JSON }}
        run: |
          python reserva_padel_git.py
